# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.allowMissingModules = true;
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_rpi4;
  hardware.raspberry-pi."4".fkms-3d.enable = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
    fsType = "ext4";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  # for Raspberry Pi, we use wpa_supplicant and declarative network
  #   configuration, instead of NetworkManager, because sometimes it works in
  #   a headless environment, making connecting nto wireless networks via
  #   NetworkManager hard.
  networking.networkmanager.enable = false;
  networking.wireless.enable = true;
  networking.dhcpcd.enable = true;
  networking.wireless.networks = {
    "ChinaNet-P7NZVZ" = {
      pskRaw = "ec7dedff625021dc199f5469c3ab76addc4367f89d729bd08725c9658b329a16";
    };
    "Redmi Note 11T Pro" = {
      pskRaw = "a16b1b5a84164de629bc20c722f79dbeb82ef320fd369b23c79df71c241543f9";
    };
  };
}
